title: Nihaal 
author: Abdun Nihaal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nifey.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Nihaal_an
github_username:  nifey

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
